# Generated by Django 5.0.3 on 2024-04-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_book_price_alter_card_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='card',
            name='price',
            field=models.TextField(default=''),
        ),
    ]
